# Generated by Django 3.2.5 on 2022-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cc', models.IntegerField(max_length=10)),
                ('correo', models.EmailField(max_length=30)),
                ('tipo_cliente', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('tipo_solicitud', models.CharField(choices=[('PREGUNTA', 'P'), ('QUEJA', 'Q'), ('RECLAMO', 'R'), ('SOLICITUD', 'S')], max_length=9, null=True)),
                ('asunto', models.CharField(max_length=20, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('fecha_solicitud', models.DateField(null=True)),
            ],
        ),
    ]
