# Generated by Django 3.2.5 on 2022-04-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prqs',
            name='cc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.usuario'),
        ),
    ]
