# Generated by Django 3.2.5 on 2022-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_alter_prqs_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='prqs',
            name='estado_pqrs',
            field=models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('PROGRESO', 'PROGRESO'), ('CERRADO', 'CERRADO')], default='ABIERTO', max_length=8),
        ),
    ]
