# Generated by Django 3.2.5 on 2022-04-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0006_alter_prqs_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prqs',
            name='cc',
            field=models.IntegerField(max_length=10),
        ),
    ]
