# Generated by Django 3.2.5 on 2022-04-26 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0008_alter_prqs_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prqs',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='prqs',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='prqs',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='prqs',
            name='tipo_cliente',
        ),
        migrations.AlterField(
            model_name='prqs',
            name='cc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.usuario', to_field='cc'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cc',
            field=models.IntegerField(unique=True),
        ),
    ]
