# Generated by Django 3.2.5 on 2022-04-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0009_auto_20220425_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prqs',
            old_name='cc',
            new_name='usuario',
        ),
    ]
