# Generated by Django 3.2.5 on 2022-04-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0010_rename_cc_prqs_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prqs',
            old_name='usuario',
            new_name='cedula_usuario',
        ),
    ]
