# Generated by Django 3.2.5 on 2022-04-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0011_rename_usuario_prqs_cedula_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prqs',
            old_name='cedula_usuario',
            new_name='usuario',
        ),
    ]
