# Generated by Django 3.2.5 on 2022-04-28 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0012_rename_cedula_usuario_prqs_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prqs',
            name='tratamiento',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
