# Generated by Django 4.0.4 on 2022-05-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0013_prqs_tratamiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prqs',
            new_name='pqrs',
        ),
    ]
