# Generated by Django 4.0.4 on 2022-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0014_rename_prqs_pqrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='tratamiento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
