# Generated by Django 4.0.4 on 2022-05-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0015_alter_pqrs_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='piano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_piano', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
