# Generated by Django 4.0.4 on 2022-05-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0016_piano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='image',
            field=models.ImageField(upload_to='pianos'),
        ),
    ]
