# Generated by Django 4.0.4 on 2022-05-20 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0017_alter_piano_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='contenido',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
