# Generated by Django 4.0.4 on 2022-05-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0019_alter_piano_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='contenido',
            field=models.CharField(max_length=500),
        ),
    ]
