# Generated by Django 4.0.4 on 2022-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0020_alter_piano_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='tipo_solicitud',
            field=models.CharField(choices=[('PREGUNTA', 'P'), ('QUEJA', 'Q'), ('RECLAMO', 'R'), ('SUGERENCIAS', 'S')], max_length=11, null=True),
        ),
    ]
