# Generated by Django 4.0.4 on 2022-05-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0021_alter_pqrs_tipo_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendar_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto_cita', models.CharField(max_length=20)),
                ('fecha_cita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.usuario', to_field='cc')),
            ],
        ),
    ]
