# Generated by Django 4.0.4 on 2022-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0022_agendar_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar_cita',
            name='asunto_cita',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='fecha_cita',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='hora_salida',
            field=models.TimeField(null=True),
        ),
    ]
