# Generated by Django 4.0.4 on 2022-05-25 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0023_alter_agendar_cita_asunto_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar_cita',
            name='asunto_cita',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='fecha_cita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendar_cita',
            name='hora_salida',
            field=models.TimeField(),
        ),
    ]
