# Generated by Django 4.0.4 on 2022-05-26 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0024_alter_agendar_cita_asunto_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendar_cita',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='agendar_cita',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='agendar_cita',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='agendar_cita',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendar_cita',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
